// CreateStepsStyles.js - All styles for the CreateSteps component

// Chrome detection function
const isChrome = () => {
    return navigator.userAgent.includes('Chrome') && !navigator.userAgent.includes('Edg') && !navigator.userAgent.includes('Safari');
};

export const styles = {
    pageContainer: {
        display: 'flex',
        height: '100%',
        fontFamily: "'Inter', sans-serif", 
        color: '#D9D9D9',
        backgroundColor: '#000000',
        ...(isChrome() && {
            width: '100vw',
            overflow: 'hidden',
        }),
    },
    videoTimelineContainer: {
        display: 'flex',
        flexDirection: 'column',
        height: '100vh',
        fontFamily: "'Inter', sans-serif", 
        color: '#D9D9D9',
        backgroundColor: '#000000',
        ...(isChrome() && {
            width: '100vw',
            height: '100vh',
            overflow: 'hidden',
        }),
    },
    videoTimelineLayout: {
        display: 'flex',
        flex: 1,
        overflow: 'hidden',
        ...(isChrome() && {
            width: '100%',
            minWidth: '0',
        }),
    },
    leftPanel: {
        width: '40%',
        display: 'flex',
        flexDirection: 'column',
        backgroundColor: '#000000',
        borderRight: '1px solid #D9D9D9',
        ...(isChrome() && {
            width: '25%',
            minWidth: '260px',
            maxWidth: '300px',
            flexShrink: 0,
        }),
    },
    rightPanel: {
        width: '60%',
        display: 'flex',
        flexDirection: 'column',
        backgroundColor: '#000000',
        ...(isChrome() && {
            width: '75%',
            minWidth: '0',
            flex: 1,
        }),
    },
    mainContent: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
        ...(isChrome() && {
            width: '100%',
            minWidth: '0',
        }),
    },
    header: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '20px 30px',
        backgroundColor: '#000000',
        borderBottom: '1px solid #D9D9D9',
        boxShadow: '0 1px 3px rgba(0,0,0,0.3)',
        ...(isChrome() && {
            padding: '12px 16px',
            width: '100%',
            minWidth: '0',
            boxSizing: 'border-box',
        }),
    },
    pageTitle: {
        fontSize: '1.8rem', 
        fontWeight: 'bold',
        color: '#F1C232', // Gold for main title
        ...(isChrome() && {
            fontSize: '1.6rem',
        }),
    },
    projectNameHighlight: {
        color: '#F1C232', 
    },
    backLink: {
        fontSize: '0.9rem',
        color: '#0000FF',
        textDecoration: 'none',
        padding: '8px 16px',
        borderRadius: '6px',
        backgroundColor: '#000000',
        border: '1px solid #0000FF',
        transition: 'all 0.2s',
    },
    timelineContainer: {
        padding: '20px 30px',
        backgroundColor: '#000000',
        borderBottom: '1px solid #D9D9D9',
        minHeight: '120px',
    },
    timeline: {
        display: 'flex',
        gap: '12px',
        overflowX: 'auto',
        padding: '10px 0',
    },
    stepCard: {
        minWidth: '200px',
        backgroundColor: '#000000',
        border: '2px solid #D9D9D9',
        borderRadius: '8px',
        padding: '12px',
        cursor: 'pointer',
        transition: 'all 0.2s',
        position: 'relative',
    },
    stepCardActive: {
        border: '2px solid #0000FF',
        backgroundColor: '#1a1a1a',
        boxShadow: '0 4px 12px rgba(0,0,0,0.25)',
    },
    stepCardEmpty: {
        minWidth: '200px',
        backgroundColor: '#222222',
        border: '2px dashed #D9D9D9',
        borderRadius: '8px',
        padding: '20px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        color: '#D9D9D9',
        fontSize: '0.9rem',
        cursor: 'pointer',
        transition: 'all 0.2s',
    },
    contentArea: {
        flex: 1,
        display: 'flex',
        overflow: 'hidden',
    },
    tabContent: {
        flex: 1,
        padding: '30px',
        overflowY: 'auto',
        backgroundColor: '#000000',
    },
    errorMessage: {
        padding: '12px',
        backgroundColor: '#2d0000', 
        border: '1px solid #FFCCCC',
        color: '#D8000C',
        borderRadius: '8px',
        fontSize: '0.9rem',
        marginBottom: '20px',
    },
    successMessage: {
        padding: '12px',
        backgroundColor: '#003300', 
        border: '1px solid #CCFFCC',
        color: '#10b981',
        borderRadius: '8px',
        fontSize: '0.9rem',
        marginBottom: '20px',
        cursor: 'pointer',
    },
    card: {
        padding: '20px',
        border: '1px solid #D9D9D9', 
        borderRadius: '12px',
        boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
        backgroundColor: '#000000',
        marginBottom: '20px',
        ...(isChrome() && {
            padding: '8px',
            marginBottom: '8px',
            width: '100%',
            minWidth: '0',
            boxSizing: 'border-box',
        }),
    },
    sectionTitle: {
        fontSize: '1.4rem',
        fontWeight: '600',
        color: '#F1C232', // Gold for section titles
        marginBottom: '16px',
        paddingBottom: '8px',
        borderBottom: '1px solid #D9D9D9',
        ...(isChrome() && {
            fontSize: '1.2rem',
            marginBottom: '12px',
            width: '100%',
            minWidth: '0',
        }),
    },
    inputLabel: {
        display: 'block',
        fontSize: '0.875rem',
        fontWeight: '500',
        color: '#D9D9D9', 
        marginBottom: '6px',
        ...(isChrome() && {
            fontSize: '0.8rem',
            marginBottom: '4px',
        }),
    },
    inputField: {
        width: '100%',
        padding: '10px 12px',
        fontSize: '0.9rem',
        color: '#D9D9D9',
        backgroundColor: '#000000', 
        border: '1px solid #D9D9D9', 
        borderRadius: '8px',
        boxShadow: 'inset 0 1px 2px rgba(0,0,0,0.15)',
        transition: 'border-color 0.2s ease-in-out, box-shadow 0.2s ease-in-out',
        boxSizing: 'border-box', 
        ...(isChrome() && {
            padding: '6px 8px',
            fontSize: '0.8rem',
            width: '100%',
            minWidth: '0',
            boxSizing: 'border-box',
        }),
    },
    textareaField: {
        width: '100%',
        padding: '10px 12px',
        fontSize: '0.9rem',
        color: '#D9D9D9',
        backgroundColor: '#000000',
        border: '1px solid #D9D9D9',
        borderRadius: '8px',
        boxShadow: 'inset 0 1px 2px rgba(0,0,0,0.15)',
        transition: 'border-color 0.2s ease-in-out, box-shadow 0.2s ease-in-out',
        minHeight: '80px',
        boxSizing: 'border-box',
        ...(isChrome() && {
            padding: '6px 8px',
            fontSize: '0.8rem',
            minHeight: '60px',
            width: '100%',
            minWidth: '0',
            boxSizing: 'border-box',
        }),
    },
    button: {
        padding: '10px 18px',
        fontSize: '0.9rem',
        fontWeight: '600',
        borderRadius: '8px',
        border: 'none',
        cursor: 'pointer',
        transition: 'background-color 0.2s ease-in-out, transform 0.1s ease',
        boxShadow: '0 2px 4px rgba(0,0,0,0.15)',
        ...(isChrome() && {
            width: 'auto',
            minWidth: '0',
        }),
    },
    buttonPrimary: {
        backgroundColor: '#F1C232', // Gold for primary actions
        color: '#000000',
    },
    buttonSecondary: {
        backgroundColor: '#0000FF', 
        color: '#D9D9D9',
    },
    buttonSecondarySm: {
        padding: '6px 12px',
        fontSize: '0.8rem',
        backgroundColor: '#0000FF',
        color: '#D9D9D9',
    },
    buttonDisabled: {
        backgroundColor: '#222222', 
        color: '#D9D9D9',
        cursor: 'not-allowed',
        opacity: 0.7,
    },
    fileInput: {
        width: '100%',
        fontSize: '0.9rem',
        color: '#D9D9D9',
        padding: '8px 0',
        boxSizing: 'border-box',
        backgroundColor: '#000000',
        border: '1px solid #D9D9D9',
    },
    videoPlayer: {
        width: '100%',
        borderRadius: '8px',
        backgroundColor: '#000000',
        aspectRatio: '16 / 9',
        minHeight: '300px', 
    },
    // New styles for video-timeline layout
    leftPanelContent: {
        flex: 1,
        padding: '20px',
        overflowY: 'auto',
        ...(isChrome() && {
            padding: '8px',
            width: '100%',
            minWidth: '0',
            boxSizing: 'border-box',
        }),
    },
    finalizeContainer: {
        flex: 1,
        padding: '40px',
        overflowY: 'auto',
        backgroundColor: '#000000',
        minHeight: '100vh',
        ...(isChrome() && {
            padding: '16px',
            width: '100%',
            minWidth: '0',
            boxSizing: 'border-box',
        }),
    },
    tabNavigation: {
        display: 'flex',
        borderBottom: '2px solid #D9D9D9',
        backgroundColor: '#000000',
        borderTopLeftRadius: '8px',
        borderTopRightRadius: '8px',
        padding: '0 20px',
        ...(isChrome() && {
            padding: '0 8px',
            width: '100%',
            minWidth: '0',
            boxSizing: 'border-box',
        }),
    },
    tabButton: {
        padding: '12px 16px',
        fontSize: '0.9rem',
        fontWeight: '500',
        border: 'none',
        backgroundColor: 'transparent',
        color: '#D9D9D9',
        cursor: 'pointer',
        transition: 'all 0.2s',
        borderBottomWidth: '2px',
        borderBottomStyle: 'solid',
        borderBottomColor: 'transparent',
        position: 'relative',
        ...(isChrome() && {
            padding: '8px 10px',
            fontSize: '0.8rem',
            flex: 1,
            minWidth: '0',
        }),
    },
    tabButtonActive: {
        color: '#000000',
        backgroundColor: '#F1C232',
        borderBottomColor: '#0000FF',
        fontWeight: '600',
        borderRadius: '6px 6px 0 0',
    },
    videoSection: {
        padding: '20px',
        borderBottom: '1px solid #D9D9D9',
        ...(isChrome() && {
            padding: '12px',
            width: '100%',
            minWidth: '0',
            boxSizing: 'border-box',
        }),
    },
    videoContainer: {
        marginBottom: '16px',
        ...(isChrome() && {
            marginBottom: '12px',
        }),
    },
    videoSelection: {
        display: 'flex',
        gap: '8px',
        marginBottom: '16px',
        flexWrap: 'wrap',
        ...(isChrome() && {
            gap: '6px',
            marginBottom: '12px',
        }),
    },
    videoSelectButton: {
        padding: '6px 12px',
        fontSize: '0.8rem',
        fontWeight: '500',
        border: '1px solid #D9D9D9',
        borderRadius: '6px',
        backgroundColor: '#000000',
        color: '#D9D9D9',
        cursor: 'pointer',
        transition: 'all 0.2s',
    },
    videoSelectButtonActive: {
        backgroundColor: '#0000FF',
        color: '#D9D9D9',
        border: '1px solid #0000FF',
    },
    videoControls: {
        display: 'flex',
        gap: '8px',
        marginTop: '12px',
        flexWrap: 'wrap',
        ...(isChrome() && {
            width: '100%',
            minWidth: '0',
        }),
    },
    noVideoMessage: {
        padding: '40px',
        textAlign: 'center',
        color: '#D9D9D9',
        backgroundColor: '#000000',
        fontSize: '0.9rem',
    },
    stepsSection: {
        flex: 1,
        padding: '20px',
        overflowY: 'auto',
        ...(isChrome() && {
            padding: '12px',
            width: '100%',
            minWidth: '0',
            boxSizing: 'border-box',
        }),
    },
    stepsSectionHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '16px',
        ...(isChrome() && {
            marginBottom: '12px',
            gap: '8px',
        }),
    },
    stepsSectionTitle: {
        fontSize: '1.1rem',
        fontWeight: '600',
        color: '#F1C232',
        ...(isChrome() && {
            width: '100%',
            minWidth: '0',
        }),
    },
    stepsList: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    stepItem: {
        padding: '12px',
        border: '1px solid #D9D9D9',
        borderRadius: '8px',
        backgroundColor: '#000000',
        cursor: 'pointer',
        transition: 'all 0.2s',
        ...(isChrome() && {
            width: '100%',
            minWidth: '0',
        }),
    },
    stepItemActive: {
        border: '1px solid #0000FF',
        backgroundColor: '#F1C232',
        boxShadow: '0 2px 8px rgba(0,0,0,0.25)',
        color: '#000000',
    },
    stepItemHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '4px',
    },
    stepItemNumber: {
        fontSize: '0.9rem',
        fontWeight: '600',
        color: '#F1C232',
    },
    stepItemNumberActive: {
        fontSize: '0.9rem',
        fontWeight: '600',
        color: '#000000',
    },
    stepItemTime: {
        fontSize: '0.8rem',
        color: '#D9D9D9',
    },
    stepItemTimeActive: {
        fontSize: '0.8rem',
        color: '#000000',
    },
    stepItemName: {
        fontSize: '0.9rem',
        color: '#D9D9D9',
    },
    stepItemNameActive: {
        fontSize: '0.9rem',
        color: '#000000',
    },
    floatingActionButton: {
        position: 'fixed',
        bottom: '30px',
        right: '30px',
        zIndex: 1000,
        backgroundColor: '#F1C232',
        color: '#000000',
        border: 'none',
        boxShadow: '0 4px 12px rgba(0,0,0,0.25)',
    },
    // Video timeline (under video)
    videoTimelineUnderVideo: {
        marginTop: '16px',
        marginBottom: '16px',
    },
    videoTimelineTrack: {
        position: 'relative',
        height: '30px',
        backgroundColor: '#f1f5f9',
        borderRadius: '4px',
        marginBottom: '8px',
        cursor: 'pointer',
    },
    videoTimelineControls: {
        display: 'flex',
        gap: '6px',
        justifyContent: 'center',
    },
    annotationAreaContainer: {
        width: '100%',
        marginLeft: 'auto',
        marginRight: 'auto',
        position: 'relative', 
        border: '1px dashed #cbd5e1',
        padding: '10px',
        borderRadius: '8px',
        backgroundColor: '#f8f9fa'
    },
    listItem: {
        padding: '10px 0',
        borderBottom: '1px solid #e2e8f0',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    listItemLast: {
        borderBottom: 'none',
    },
    removeButton: {
        color: '#e53e3e', 
        backgroundColor: 'transparent',
        border: 'none',
        padding: '4px 8px',
        fontSize: '0.8rem',
        fontWeight: 'bold',
        cursor: 'pointer',
    },
    timeDisplay: {
        fontSize: '0.8rem',
        color: '#D9D9D9',
        marginTop: '4px',
        backgroundColor: '#e9ecef',
        padding: '4px 8px',
        borderRadius: '4px',
        display: 'inline-block',
    },
    flexWrapGap2: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: '8px',
    },
    itemsCenter: {
        alignItems: 'center',
    },
    subSection: {
        paddingTop: '16px',
        borderTop: '1px solid #e9ecef', 
        marginTop: '20px',
    },
    subSectionTitle: {
        fontSize: '1.1rem',
        fontWeight: '600',
        color: '#D9D9D9',
        marginBottom: '12px',
    },
    // Action buttons
    actionButtons: {
        position: 'fixed',
        bottom: '20px',
        right: '20px',
        display: 'flex',
        gap: '12px',
        zIndex: 1000,
    },
    floatingButton: {
        padding: '12px 24px',
        fontSize: '1rem',
        fontWeight: '600',
        borderRadius: '50px',
        border: 'none',
        cursor: 'pointer',
        boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
        transition: 'all 0.2s',
    },
    saveButton: {
        backgroundColor: '#0000FF',
        color: 'white',
    },
    finishButton: {
        backgroundColor: '#27ae60',
        color: 'white',
    },
    // Timeline styles (fixed position)
    timelineFixed: {
        position: 'fixed',
        bottom: 0,
        left: 0,
        right: 0,
        height: '120px',
        backgroundColor: '#18181b', // darker background
        borderTop: '2px solid #F1C232', // gold border
        padding: '16px 20px',
        zIndex: 1000,
    },
    timelineTrack: {
        position: 'relative',
        height: '40px',
        backgroundColor: '#232323', // dark background
        borderRadius: '4px',
        marginBottom: '12px',
        cursor: 'pointer',
    },
    timelineBackground: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: '#18181b', // match timelineFixed
        borderRadius: '4px',
    },
    currentTimeIndicator: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        width: '2px',
        backgroundColor: '#F1C232', // gold
        zIndex: 3,
        boxShadow: '0 0 8px #F1C232',
    },
    timelineStep: {
        position: 'absolute',
        top: '4px',
        bottom: '4px',
        backgroundColor: '#0000FF', // blue
        borderRadius: '2px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 2,
        boxShadow: '0 2px 8px #0000FF44',
    },
    timelineStepLabel: {
        fontSize: '0.7rem',
        fontWeight: '700',
        color: '#F1C232', // gold
        textShadow: '0 2px 8px #000',
    },
    timelineMarker: {
        position: 'absolute',
        top: '-8px',
        bottom: '-8px',
        width: '12px',
        cursor: 'ew-resize',
        zIndex: 4,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
    },
    startMarker: {
        transform: 'translateX(-6px)',
    },
    endMarker: {
        transform: 'translateX(-6px)',
    },
    markerHandle: {
        width: '12px',
        height: '12px',
        borderRadius: '50%',
        backgroundColor: '#F1C232', // gold
        color: '#000000', // black text
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '0.7rem',
        fontWeight: 'bold',
        boxShadow: '0 2px 4px #F1C23288',
    },
    markerTime: {
        fontSize: '0.7rem',
        color: '#F1C232', // gold
        marginTop: '2px',
        whiteSpace: 'nowrap',
        textShadow: '0 2px 8px #000',
    },
    selectionArea: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        backgroundColor: 'rgba(241, 194, 50, 0.18)', // gold semi-transparent
        borderRadius: '4px',
        zIndex: 1,
    },
    // Floating Timeline styles (iMovie-like)
    floatingTimeline: {
        position: 'fixed',
        bottom: 0,
        left: '256px', // Account for sidebar width
        right: 0,
        height: '140px',
        backgroundColor: '#18181b', // darker
        borderTop: '2px solid #F1C232',
        zIndex: 1000,
        boxShadow: '0 -4px 20px #000',
        transition: 'all 0.3s ease',
    },
    floatingTimelineCollapsed: {
        height: '60px',
    },
    timelineHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '8px 16px',
        borderBottom: '1px solid #333',
        backgroundColor: '#18181b',
    },
    timelineTitle: {
        fontSize: '0.9rem',
        fontWeight: '700',
        color: '#F1C232',
        letterSpacing: '0.5px',
    },
    timelineControls: {
        display: 'flex',
        gap: '8px',
        alignItems: 'center',
    },
    zoomControl: {
        display: 'flex',
        alignItems: 'center',
        gap: '4px',
    },
    zoomButton: {
        backgroundColor: '#232323',
        color: '#F1C232',
        border: '1px solid #F1C232',
        borderRadius: '4px',
        padding: '4px 8px',
        fontSize: '0.8rem',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
    },
    zoomButtonHover: {
        backgroundColor: '#F1C232',
        color: '#000000',
    },
    zoomLevel: {
        fontSize: '0.8rem',
        color: '#F1C232',
        minWidth: '40px',
        textAlign: 'center',
    },
    timelineBody: {
        padding: '12px 16px',
        height: 'calc(100% - 40px)',
        overflow: 'hidden',
    },
    timelineScrollContainer: {
        height: '100%',
        overflowX: 'auto',
        overflowY: 'hidden',
        position: 'relative',
    },
    timelineRuler: {
        position: 'absolute',
        top: '-20px',
        left: 0,
        right: 0,
        height: '20px',
        backgroundColor: 'transparent',
        borderBottom: '1px solid #F1C232',
        display: 'flex',
        alignItems: 'flex-end',
        fontSize: '0.7rem',
        color: '#F1C232',
    },
    rulerMark: {
        position: 'absolute',
        bottom: '2px',
        width: '1px',
        height: '8px',
        backgroundColor: '#F1C232',
    },
    rulerLabel: {
        position: 'absolute',
        bottom: '12px',
        transform: 'translateX(-50%)',
        fontSize: '0.7rem',
        color: '#F1C232',
        fontWeight: '700',
        textShadow: '0 2px 8px #000',
    },
    timelineStepHover: {
        backgroundColor: '#F1C232',
        transform: 'scaleY(1.1)',
        color: '#000000',
    },
    timelineActionButtons: {
        display: 'flex',
        gap: '6px',
        marginTop: '8px',
        justifyContent: 'center',
    },
    timelineButton: {
        backgroundColor: '#232323',
        color: '#F1C232',
        border: '1px solid #F1C232',
        borderRadius: '4px',
        padding: '6px 12px',
        fontSize: '0.8rem',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
    },
    timelineButtonPrimary: {
        backgroundColor: '#0000FF',
        color: '#F1C232',
        borderColor: '#0000FF',
    },
    timelineButtonSecondary: {
        backgroundColor: '#F1C232',
        color: '#000000',
        borderColor: '#F1C232',
    },
    timelineButtonDanger: {
        backgroundColor: '#ef4444',
        color: '#F1C232',
        borderColor: '#ef4444',
    },
    timelineButtonHover: {
        transform: 'translateY(-1px)',
        boxShadow: '0 2px 4px #F1C23288',
    },
    contentPadding: {
        paddingBottom: '160px', // Add padding to prevent content from being hidden behind timeline
    },
    timelineToggle: {
        position: 'fixed',
        bottom: '20px',
        right: '20px',
        backgroundColor: '#F1C232',
        color: '#000000',
        border: 'none',
        borderRadius: '50%',
        width: '50px',
        height: '50px',
        fontSize: '1.2rem',
        cursor: 'pointer',
        zIndex: 1001,
        boxShadow: '0 4px 12px rgba(0,0,0,0.3)',
        transition: 'all 0.2s ease',
    },
    timelineToggleHover: {
        transform: 'scale(1.1)',
        boxShadow: '0 6px 16px rgba(0,0,0,0.4)',
    },
};

export const getGridStyles = (isLargeScreen) => ({
    ...styles.gridContainer,
    gridTemplateColumns: isLargeScreen ? '2fr 1fr' : '1fr', 
});

export const getMainContentStyles = (isLargeScreen) => ({
    ...styles.mainContentArea,
    gridColumn: isLargeScreen ? 'span 2 / span 2' : 'span 1 / span 1',
}); 