// CreateStepsStyles.js - All styles for the CreateSteps component
export const styles = {
    pageContainer: {
        display: 'flex',
        height: '100%',
        fontFamily: "'Inter', sans-serif", 
        color: '#333',
        backgroundColor: '#f8fafc',
    },
    videoTimelineContainer: {
        display: 'flex',
        flexDirection: 'column',
        height: '100vh',
        fontFamily: "'Inter', sans-serif", 
        color: '#333',
        backgroundColor: '#f8fafc',
    },
    videoTimelineLayout: {
        display: 'flex',
        flex: 1,
        overflow: 'hidden',
    },
    leftPanel: {
        width: '40%',
        display: 'flex',
        flexDirection: 'column',
        backgroundColor: 'white',
        borderRight: '1px solid #e2e8f0',
    },
    rightPanel: {
        width: '60%',
        display: 'flex',
        flexDirection: 'column',
        backgroundColor: 'white',
    },
    mainContent: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
    },
    header: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '20px 30px',
        backgroundColor: 'white',
        borderBottom: '1px solid #e2e8f0',
        boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
    },
    pageTitle: {
        fontSize: '1.8rem', 
        fontWeight: 'bold',
        color: '#2c3e50',
    },
    projectNameHighlight: {
        color: '#4A90E2', 
    },
    backLink: {
        fontSize: '0.9rem',
        color: '#4A90E2',
        textDecoration: 'none',
        padding: '8px 16px',
        borderRadius: '6px',
        backgroundColor: '#f0f9ff',
        transition: 'all 0.2s',
    },
    timelineContainer: {
        padding: '20px 30px',
        backgroundColor: 'white',
        borderBottom: '1px solid #e2e8f0',
        minHeight: '120px',
    },
    timeline: {
        display: 'flex',
        gap: '12px',
        overflowX: 'auto',
        padding: '10px 0',
    },
    stepCard: {
        minWidth: '200px',
        backgroundColor: '#f8fafc',
        border: '2px solid #e2e8f0',
        borderRadius: '8px',
        padding: '12px',
        cursor: 'pointer',
        transition: 'all 0.2s',
        position: 'relative',
    },
    stepCardActive: {
        borderColor: '#4A90E2',
        backgroundColor: '#e3f2fd',
        boxShadow: '0 4px 12px rgba(74, 144, 226, 0.15)',
    },
    stepCardEmpty: {
        minWidth: '200px',
        backgroundColor: '#f1f5f9',
        border: '2px dashed #cbd5e1',
        borderRadius: '8px',
        padding: '20px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        color: '#64748b',
        fontSize: '0.9rem',
        cursor: 'pointer',
        transition: 'all 0.2s',
    },
    contentArea: {
        flex: 1,
        display: 'flex',
        overflow: 'hidden',
    },
    tabContent: {
        flex: 1,
        padding: '30px',
        overflowY: 'auto',
        backgroundColor: 'white',
    },
    errorMessage: {
        padding: '12px',
        backgroundColor: '#FFF0F0', 
        border: '1px solid #FFCCCC',
        color: '#D8000C',
        borderRadius: '8px',
        fontSize: '0.9rem',
        marginBottom: '20px',
    },
    successMessage: {
        padding: '12px',
        backgroundColor: '#F0FFF0', 
        border: '1px solid #CCFFCC',
        color: '#008000',
        borderRadius: '8px',
        fontSize: '0.9rem',
        marginBottom: '20px',
        cursor: 'pointer',
    },
    card: {
        padding: '20px',
        border: '1px solid #e2e8f0', 
        borderRadius: '12px',
        boxShadow: '0 4px 12px rgba(0, 0, 0, 0.05)',
        backgroundColor: '#ffffff',
        marginBottom: '20px',
    },
    sectionTitle: {
        fontSize: '1.4rem',
        fontWeight: '600',
        color: '#34495e',
        marginBottom: '16px',
        paddingBottom: '8px',
        borderBottom: '1px solid #eee'
    },
    inputLabel: {
        display: 'block',
        fontSize: '0.875rem',
        fontWeight: '500',
        color: '#4a5568', 
        marginBottom: '6px',
    },
    inputField: {
        width: '100%',
        padding: '10px 12px',
        fontSize: '0.9rem',
        color: '#4a5568',
        backgroundColor: '#f8fafc', 
        border: '1px solid #cbd5e1', 
        borderRadius: '8px',
        boxShadow: 'inset 0 1px 2px rgba(0,0,0,0.05)',
        transition: 'border-color 0.2s ease-in-out, box-shadow 0.2s ease-in-out',
        boxSizing: 'border-box', 
    },
    textareaField: {
        width: '100%',
        padding: '10px 12px',
        fontSize: '0.9rem',
        color: '#4a5568',
        backgroundColor: '#f8fafc',
        border: '1px solid #cbd5e1',
        borderRadius: '8px',
        boxShadow: 'inset 0 1px 2px rgba(0,0,0,0.05)',
        transition: 'border-color 0.2s ease-in-out, box-shadow 0.2s ease-in-out',
        minHeight: '80px',
        boxSizing: 'border-box',
    },
    button: {
        padding: '10px 18px',
        fontSize: '0.9rem',
        fontWeight: '600',
        borderRadius: '8px',
        border: 'none',
        cursor: 'pointer',
        transition: 'background-color 0.2s ease-in-out, transform 0.1s ease',
        boxShadow: '0 2px 4px rgba(0,0,0,0.05)',
    },
    buttonPrimary: {
        backgroundColor: '#4A90E2', 
        color: 'white',
    },
    buttonSecondary: {
        backgroundColor: '#6c757d', 
        color: 'white',
    },
    buttonSecondarySm: {
        padding: '6px 12px',
        fontSize: '0.8rem',
        backgroundColor: '#6c757d',
        color: 'white',
    },
    buttonDisabled: {
        backgroundColor: '#e9ecef', 
        color: '#6c757d',
        cursor: 'not-allowed',
        opacity: 0.7,
    },
    fileInput: {
        width: '100%',
        fontSize: '0.9rem',
        color: '#4a5568',
        padding: '8px 0',
        boxSizing: 'border-box',
    },
    videoPlayer: {
        width: '100%',
        borderRadius: '8px',
        backgroundColor: '#000',
        aspectRatio: '16 / 9',
        minHeight: '300px', 
    },
    // New styles for video-timeline layout
    leftPanelContent: {
        flex: 1,
        padding: '20px',
        overflowY: 'auto',
    },
    finalizeContainer: {
        flex: 1,
        padding: '40px',
        overflowY: 'auto',
        backgroundColor: '#f8fafc',
        minHeight: '100vh',
    },
    tabNavigation: {
        display: 'flex',
        borderBottom: '2px solid #e2e8f0',
        backgroundColor: '#f8fafc',
        borderTopLeftRadius: '8px',
        borderTopRightRadius: '8px',
        padding: '0 20px',
    },
    tabButton: {
        padding: '12px 16px',
        fontSize: '0.9rem',
        fontWeight: '500',
        border: 'none',
        background: 'none',
        color: '#6b7280',
        cursor: 'pointer',
        transition: 'all 0.2s',
        borderBottom: '2px solid transparent',
        position: 'relative',
    },
    tabButtonActive: {
        color: '#4A90E2',
        borderBottomColor: '#4A90E2',
        fontWeight: '600',
    },
    videoSection: {
        padding: '20px',
        borderBottom: '1px solid #e2e8f0',
    },
    videoContainer: {
        marginBottom: '16px',
    },
    videoSelection: {
        display: 'flex',
        gap: '8px',
        marginBottom: '16px',
        flexWrap: 'wrap',
    },
    videoSelectButton: {
        padding: '6px 12px',
        fontSize: '0.8rem',
        fontWeight: '500',
        border: '1px solid #e2e8f0',
        borderRadius: '6px',
        backgroundColor: '#f8fafc',
        color: '#6b7280',
        cursor: 'pointer',
        transition: 'all 0.2s',
    },
    videoSelectButtonActive: {
        backgroundColor: '#4A90E2',
        color: 'white',
        borderColor: '#4A90E2',
    },
    videoControls: {
        display: 'flex',
        gap: '8px',
        marginTop: '12px',
        flexWrap: 'wrap',
    },
    noVideoMessage: {
        padding: '40px',
        textAlign: 'center',
        color: '#6b7280',
        fontSize: '0.9rem',
    },
    stepsSection: {
        flex: 1,
        padding: '20px',
        overflowY: 'auto',
    },
    stepsSectionHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '16px',
    },
    stepsSectionTitle: {
        fontSize: '1.1rem',
        fontWeight: '600',
        color: '#2d3748',
    },
    stepsList: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    stepItem: {
        padding: '12px',
        border: '1px solid #e2e8f0',
        borderRadius: '8px',
        backgroundColor: '#f8fafc',
        cursor: 'pointer',
        transition: 'all 0.2s',
    },
    stepItemActive: {
        borderColor: '#4A90E2',
        backgroundColor: '#e3f2fd',
        boxShadow: '0 2px 8px rgba(74, 144, 226, 0.15)',
    },
    stepItemHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '4px',
    },
    stepItemNumber: {
        fontSize: '0.9rem',
        fontWeight: '600',
        color: '#2d3748',
    },
    stepItemTime: {
        fontSize: '0.8rem',
        color: '#6b7280',
    },
    stepItemName: {
        fontSize: '0.9rem',
        color: '#4a5568',
    },
    floatingActionButton: {
        position: 'fixed',
        bottom: '30px',
        right: '30px',
        zIndex: 1000,
    },
    // Video timeline (under video)
    videoTimelineUnderVideo: {
        marginTop: '16px',
        marginBottom: '16px',
    },
    videoTimelineTrack: {
        position: 'relative',
        height: '30px',
        backgroundColor: '#f1f5f9',
        borderRadius: '4px',
        marginBottom: '8px',
        cursor: 'pointer',
    },
    videoTimelineControls: {
        display: 'flex',
        gap: '6px',
        justifyContent: 'center',
    },
    annotationAreaContainer: {
        width: '100%',
        margin: '0 auto',
        position: 'relative', 
        border: '1px dashed #cbd5e1',
        padding: '10px',
        borderRadius: '8px',
        backgroundColor: '#f8f9fa'
    },
    listItem: {
        padding: '10px 0',
        borderBottom: '1px solid #e2e8f0',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    listItemLast: {
        borderBottom: 'none',
    },
    removeButton: {
        color: '#e53e3e', 
        backgroundColor: 'transparent',
        border: 'none',
        padding: '4px 8px',
        fontSize: '0.8rem',
        fontWeight: 'bold',
        cursor: 'pointer',
    },
    timeDisplay: {
        fontSize: '0.8rem',
        color: '#4a5568',
        marginTop: '4px',
        backgroundColor: '#e9ecef',
        padding: '4px 8px',
        borderRadius: '4px',
        display: 'inline-block',
    },
    flexWrapGap2: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: '8px',
    },
    itemsCenter: {
        alignItems: 'center',
    },
    subSection: {
        paddingTop: '16px',
        borderTop: '1px solid #e9ecef', 
        marginTop: '20px',
    },
    subSectionTitle: {
        fontSize: '1.1rem',
        fontWeight: '600',
        color: '#34495e',
        marginBottom: '12px',
    },
    // Action buttons
    actionButtons: {
        position: 'fixed',
        bottom: '20px',
        right: '20px',
        display: 'flex',
        gap: '12px',
        zIndex: 1000,
    },
    floatingButton: {
        padding: '12px 24px',
        fontSize: '1rem',
        fontWeight: '600',
        borderRadius: '50px',
        border: 'none',
        cursor: 'pointer',
        boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
        transition: 'all 0.2s',
    },
    saveButton: {
        backgroundColor: '#4A90E2',
        color: 'white',
    },
    finishButton: {
        backgroundColor: '#27ae60',
        color: 'white',
    },
    // Timeline styles (fixed position)
    timelineFixed: {
        position: 'fixed',
        bottom: 0,
        left: 0,
        right: 0,
        height: '120px',
        backgroundColor: 'white',
        borderTop: '1px solid #e2e8f0',
        padding: '16px 20px',
        zIndex: 1000,
    },
    timelineTrack: {
        position: 'relative',
        height: '40px',
        backgroundColor: '#f1f5f9',
        borderRadius: '4px',
        marginBottom: '12px',
        cursor: 'pointer',
    },
    timelineBackground: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: '#e2e8f0',
        borderRadius: '4px',
    },
    currentTimeIndicator: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        width: '2px',
        backgroundColor: '#dc3545',
        zIndex: 3,
    },
    timelineStep: {
        position: 'absolute',
        top: '4px',
        bottom: '4px',
        backgroundColor: '#cbd5e1',
        borderRadius: '2px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 2,
    },
    timelineStepLabel: {
        fontSize: '0.7rem',
        fontWeight: '600',
        color: '#4a5568',
    },
    timelineMarker: {
        position: 'absolute',
        top: '-8px',
        bottom: '-8px',
        width: '12px',
        cursor: 'ew-resize',
        zIndex: 4,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
    },
    startMarker: {
        transform: 'translateX(-6px)',
    },
    endMarker: {
        transform: 'translateX(-6px)',
    },
    markerHandle: {
        width: '12px',
        height: '12px',
        borderRadius: '50%',
        backgroundColor: '#4A90E2',
        color: 'white',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '0.6rem',
        fontWeight: 'bold',
        boxShadow: '0 2px 4px rgba(0,0,0,0.2)',
    },
    markerTime: {
        fontSize: '0.6rem',
        color: '#6b7280',
        marginTop: '2px',
        whiteSpace: 'nowrap',
    },
    selectionArea: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        backgroundColor: 'rgba(74, 144, 226, 0.3)',
        borderRadius: '4px',
        zIndex: 1,
    },
    timelineControls: {
        display: 'flex',
        gap: '8px',
        justifyContent: 'center',
    },
};

export const getGridStyles = (isLargeScreen) => ({
    ...styles.gridContainer,
    gridTemplateColumns: isLargeScreen ? '2fr 1fr' : '1fr', 
});

export const getMainContentStyles = (isLargeScreen) => ({
    ...styles.mainContentArea,
    gridColumn: isLargeScreen ? 'span 2 / span 2' : 'span 1 / span 1',
}); 